# Generated by Django 3.1.2 on 2021-02-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='phone', max_length=50)),
                ('price', models.IntegerField(default=10)),
                ('release_date', models.DateField(default='2000-09-01')),
                ('lte_exists', models.BooleanField(default=True)),
                ('bluetooth_exists', models.BooleanField(default=True)),
                ('os', models.CharField(blank=True, choices=[('Android', 'Adroid'), ('IOS', 'Ios'), ('Other', 'Other')], max_length=15)),
                ('camera_amount', models.IntegerField(default=1)),
                ('ram', models.TextField(blank=True, choices=[('16gb', 'Gb16'), ('8gb', 'Gb8'), ('4gb', 'Gb4'), ('Other', 'Other'), ('1kb', 'Kb1')])),
                ('rom', models.TextField(blank=True, choices=[('64gb', 'Gb64'), ('128gb', 'Gb128'), ('256gb', 'Gb256'), ('Other', 'Other'), ('1kb', 'Kb1')])),
                ('screen', models.CharField(blank=True, max_length=40)),
                ('battery', models.IntegerField(default=3000)),
                ('FaceId', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nokia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='phone', max_length=50)),
                ('price', models.IntegerField(default=10)),
                ('release_date', models.DateField(default='2000-09-01')),
                ('lte_exists', models.BooleanField(default=True)),
                ('bluetooth_exists', models.BooleanField(default=True)),
                ('os', models.CharField(blank=True, choices=[('Android', 'Adroid'), ('IOS', 'Ios'), ('Other', 'Other')], max_length=15)),
                ('camera_amount', models.IntegerField(default=1)),
                ('ram', models.TextField(blank=True, choices=[('16gb', 'Gb16'), ('8gb', 'Gb8'), ('4gb', 'Gb4'), ('Other', 'Other'), ('1kb', 'Kb1')])),
                ('rom', models.TextField(blank=True, choices=[('64gb', 'Gb64'), ('128gb', 'Gb128'), ('256gb', 'Gb256'), ('Other', 'Other'), ('1kb', 'Kb1')])),
                ('screen', models.CharField(blank=True, max_length=40)),
                ('battery', models.IntegerField(default=3000)),
                ('Durability', models.TextField(default='Great', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='phone', max_length=50)),
                ('price', models.IntegerField(default=10)),
                ('release_date', models.DateField(default='2000-09-01')),
                ('lte_exists', models.BooleanField(default=True)),
                ('bluetooth_exists', models.BooleanField(default=True)),
                ('os', models.CharField(blank=True, choices=[('Android', 'Adroid'), ('IOS', 'Ios'), ('Other', 'Other')], max_length=15)),
                ('camera_amount', models.IntegerField(default=1)),
                ('ram', models.TextField(blank=True, choices=[('16gb', 'Gb16'), ('8gb', 'Gb8'), ('4gb', 'Gb4'), ('Other', 'Other'), ('1kb', 'Kb1')])),
                ('rom', models.TextField(blank=True, choices=[('64gb', 'Gb64'), ('128gb', 'Gb128'), ('256gb', 'Gb256'), ('Other', 'Other'), ('1kb', 'Kb1')])),
                ('screen', models.CharField(blank=True, max_length=40)),
                ('battery', models.IntegerField(default=3000)),
                ('Dex', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
