# Generated by Django 3.1.2 on 2021-02-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('release_date', models.DateField()),
                ('lte_exists', models.BooleanField()),
                ('bluetooth_exists', models.BooleanField()),
                ('os', models.CharField(max_length=15)),
                ('megapixels', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('screen', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
