# Generated by Django 3.1.2 on 2021-02-15 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.phone')),
                ('FaceId', models.BooleanField()),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.phone')),
                ('Dex', models.BooleanField()),
            ],
            bases=('phones.phone',),
        ),
        migrations.AddField(
            model_name='phone',
            name='battery',
            field=models.IntegerField(default=4000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.IntegerField(choices=[(16, 'Gb16'), (8, 'Gb8'), (4, 'Gb4')]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='rom',
            field=models.IntegerField(choices=[(64, 'Gb64'), (128, 'Gb128'), (256, 'Gb256')]),
        ),
    ]
