# Generated by Django 3.1.2 on 2021-02-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='ram',
            field=models.TextField(blank=True, choices=[('16GB', 'Gb16'), ('8GB', 'Gb8'), ('4GB', 'Gb4'), ('Other', 'Other'), ('1KB', 'Kb1')]),
        ),
        migrations.AlterField(
            model_name='apple',
            name='rom',
            field=models.TextField(blank=True, choices=[('64GB', 'Gb64'), ('128GB', 'Gb128'), ('256GB', 'Gb256'), ('Other', 'Other'), ('1KB', 'Kb1')]),
        ),
        migrations.AlterField(
            model_name='nokia',
            name='ram',
            field=models.TextField(blank=True, choices=[('16GB', 'Gb16'), ('8GB', 'Gb8'), ('4GB', 'Gb4'), ('Other', 'Other'), ('1KB', 'Kb1')]),
        ),
        migrations.AlterField(
            model_name='nokia',
            name='rom',
            field=models.TextField(blank=True, choices=[('64GB', 'Gb64'), ('128GB', 'Gb128'), ('256GB', 'Gb256'), ('Other', 'Other'), ('1KB', 'Kb1')]),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='ram',
            field=models.TextField(blank=True, choices=[('16GB', 'Gb16'), ('8GB', 'Gb8'), ('4GB', 'Gb4'), ('Other', 'Other'), ('1KB', 'Kb1')]),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='rom',
            field=models.TextField(blank=True, choices=[('64GB', 'Gb64'), ('128GB', 'Gb128'), ('256GB', 'Gb256'), ('Other', 'Other'), ('1KB', 'Kb1')]),
        ),
    ]
