# Generated by Django 3.1.2 on 2021-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20210215_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Iphone',
            new_name='Apple',
        ),
        migrations.AlterField(
            model_name='phone',
            name='os',
            field=models.CharField(choices=[('Android', 'Adroid'), ('IOS', 'Ios')], max_length=15),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.IntegerField(choices=[(16, '16gb'), (8, '8gb'), (4, '4gb')]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='rom',
            field=models.IntegerField(choices=[(64, '64gb'), (128, '128gb'), (256, '256gb')]),
        ),
    ]
