# Generated by Django 3.1.2 on 2021-02-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='articles',
            field=models.ManyToManyField(related_name='tags', through='articles.TagsArticles', to='articles.Article'),
        ),
    ]
