# Generated by Django 3.1.2 on 2021-02-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210222_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsarticles',
            name='is_main',
            field=models.BooleanField(blank=True, null=True, verbose_name='Главный тэг'),
        ),
    ]
