# Generated by Django 3.1.2 on 2021-02-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210222_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='articles',
            field=models.ManyToManyField(related_name='tags', through='articles.TagsArticles', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='tagsarticles',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.tags', verbose_name='Тэг'),
        ),
    ]
